version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: drupal_db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - drupal
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
  drupal:
    build:
      context: ./
      dockerfile: DockerfileDrupal
      args:
        USER_ID: ${DOCKER_UID}
        GROUP_ID: ${DOCKER_GID}
        AWS_CF_ID: ${AWS_CF_ID}
    container_name: drupal_web
    volumes:
      - ./web/themes:/var/www/html/themes
      - ./web/modules:/var/www/html/modules
      - ./web/sites:/var/www/html/sites
      - ./config:/opt/drupal/config
      - ./deployment:/opt/drupal/html
      - ./etc:/opt/drupal/etc
      - ./composer.json:/opt/drupal/composer.json:rw
      - ./composer.lock:/opt/drupal/composer.lock:rw
      - ./.env:/opt/drupal/.env:rw
      # - ./php.ini:/usr/local/etc/php/php.ini:rw
    networks:
      - drupal
    expose:
      - 80
    command: "apache2-foreground"
    depends_on:
      - mariadb
  aws:
    build:
      context: ./
      dockerfile: DockerfileAwsCli
    container_name: drupal_aws
    volumes:
      - ~/.aws:/root/.aws
      - ./deployment:/root/deployment
      - ./deployment.sh:/root/deployment.sh
      - ./web/themes/custom/pulog/common:/root/deployment/themes/custom/pulog/common
    environment:
      AWS_CLI_PROFILE: ${AWS_CLI_PROFILE}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}

networks:
  drupal:
    internal: false
    driver: bridge
    name: drupal
