<?php

use \Drupal\node\Entity\Node;
use \Drupal\path_alias\Entity\PathAlias;

/**
 * implements PathAlias move
 */
function page_static_render_path_alias_presave(PathAlias $path)
{
  /** @var \Drupal\page_static_render\PageStaticRender $render */
  $render = \Drupal::service('page_static_render.render');
  $render->pathAliasMoveCheck($path);
}

/**
 * implements Delete Node
 */
function page_static_render_node_delete(Node $node)
{
  /** @var \Drupal\page_static_render\PageStaticRender $render */
  $render = \Drupal::service('page_static_render.render');
  $render->deleteByPath($node->toUrl()->toString());
}

/**
 * implements Create Node
 */
function page_static_render_node_update(Node $node)
{
  /** @var \Drupal\page_static_render\PageStaticRender $render */
  $render = \Drupal::service('page_static_render.render');
  $render->nodeUpsertCheck($node);
}

/**
 * implements Create Node
 */
function page_static_render_node_insert(Node $node)
{
  /** @var \Drupal\page_static_render\PageStaticRender $render */
  $render = \Drupal::service('page_static_render.render');
  $render->nodeUpsertCheck($node);
}
