_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: ja
uuid: ee13fe6b-ad3b-4877-a705-6a592200d6e0
name: Pulog
mail: yuki@kato83.com
slogan: 'プログラムのブログ 略してプログ'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: ja
